WIP - updating build scripts

diff --git a/makeosx-debug b/makeosx-debug
--- a/makeosx-debug
+++ b/makeosx-debug
@@ -11,8 +11,15 @@ pushd bitcoin/src/detail/store
 make
 popd
 
-pushd deps/osx
-BUILD_TYPE="DEBUG" ./build-all.sh
+echo "Building All Joystream dependencies..."
+pushd deps/osx/
+if BUILD_TYPE="DEBUG" ./build-all.sh
+then
+   echo "Done Building Dependencies"
+else
+   echo "Building Dependencies failed"
+   exit 1
+fi
 popd
 
 mkdir -p build/osx
diff --git a/makeosx-release b/makeosx-release
--- a/makeosx-release
+++ b/makeosx-release
@@ -11,8 +11,15 @@ pushd bitcoin/src/detail/store
 make
 popd
 
+echo "Building All Joystream dependencies..."
 pushd deps/osx/
-./build-all.sh
+if ./build-all.sh
+then
+   echo "Done Building Dependencies"
+else
+   echo "Building Dependencies failed"
+   exit 1
+fi
 popd
 
 mkdir -p build/osx
diff --git a/makewin-release b/makewin-release
--- a/makewin-release
+++ b/makewin-release
@@ -14,12 +14,19 @@ pushd bitcoin/src/detail/store
 make
 popd
 
-pushd deps/win32/
-./build-all.sh
+echo "Building All Joystream dependencies..."
+pushd deps/win32
+if ./build-all.sh
+then
+   echo "Done Building Dependencies"
+else
+   echo "Building Dependencies failed"
+   exit 1
+fi
 popd
 
 mkdir -p build/win32
 cd build/win32
 qmake ../../JoyStream.pro -r -spec win32-g++ DEFINES+=QT_FORCE_ASSERTS CONFIG+=release && make release
 
-#sudo cp app/release/app.exe /media/sf_vm-shared/joystream.exe
+#application in app/release/app.exe
